# Generated by Django 4.2.7 on 2023-11-19 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('education', models.CharField(max_length=100)),
                ('storage_allocated', models.DecimalField(decimal_places=1, default=2.0, max_digits=5)),
                ('rating', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
            bases=('adminpanel.customuser',),
        ),
    ]
