# Generated by Django 4.2.7 on 2023-11-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_alter_customuser_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_provider',
            field=models.BooleanField(default=False),
        ),
    ]
